# Generated by Django 6.0 on 2026-01-09 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, verbose_name='電影名稱')),
                ('image', models.ImageField(upload_to='posters/', verbose_name='海報照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('wanted_movie', models.CharField(max_length=100, verbose_name='想交換的電影')),
                ('is_exchanged', models.BooleanField(default=False, verbose_name='是否已交換')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='持有者')),
            ],
        ),
    ]
